---

- name: testing includes

  hosts: all

  sudo: yes

  tasks:

    - include: apache.yml    

    - include: content.yml    

    - include: create_folder.yml

    - include: content.yml



- include: nginx.yml

...
#apache.yml 
---

- name: install apache2

  apt: name=apache2 update_cache=yes state=latest      

- name: displaying message

  debug: msg="you are awesome!!"
...
#create_folder.yml
---

- name: creating folder

  file: path=/home/ubuntu/folder1 state=directory
...
#content.yml
---

- name: list contents of directory in host 

  command: ls /home/ubuntu

  register: contents

- name: check dir is empty

  debug: msg="Directory is empty"

  when: contents.stdout == ""

- name: check dir has contents

  debug: msg="Directory is not empty"

  when: contents.stdout != ""
...
#nginx.yml
---

- name: installing nginx

  hosts: all

  sudo: yes

  tasks:

    - name: install nginx

      apt: name=nginx update_cache=yes state=latest      

    - name: displaying message

      debug: msg="yayy!! nginx installed"
...